version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # The actions in triage-issues.yml are updated in the Homebrew/.github repo
  ignore:
    - dependency-name: actions/stale
    - dependency-name: dessant/lock-threads
