AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FormatString:
  EnforcedStyle: percent

# we prefer compact if-else-end/case-when-end alignment
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Layout/CaseIndentation:
  EnforcedStyle: end

# Ruby 1.8 compatibility
Layout/DotPosition:
  EnforcedStyle: trailing

# TODO: re-enable in the future
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false
