language: ruby
rvm:
    - 2.3
    - 2.4
    - 2.5
cache: bundler
sudo: false
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
script:
  - bundle exec rake
  - bundle exec rubocop -D lib/
