#!/usr/bin/env bash

die() {
  echo "Error: $*" >&2
  exit 1
}

ensure() {
  "$@" \
    || die "Failed to run '$*'. Aborting."
}

# Make sure we're in the repository root.
ensure cd "${0%/*}"

# Check that Bundler is available.
which bundle > /dev/null 2>&1 \
  || die "Failed to find 'bundle' executable in PATH."

# Setup required Gems for testing.
echo ">> Checking if required Gems are installed and installing missing Gems."
if ! bundle check ; then
  ensure bundle install --path vendor/bundle
fi
echo

read -r major minor < <(ruby -e 'puts RUBY_VERSION' | awk -F. '{ print $1, $2 }')

if [[ "${major}" -eq 2 && "${minor}" -ge 2 ]]; then
    # Run rubocop.
    echo ">> Running style enforcement."
    bundle exec rubocop -DES lib/
    result="$?"
    echo ">> Done: ${result}."
else
    echo ">> Older ruby, skipping style enforcement."
fi

echo ">> Done: ${result}."

# Run the test suite.
echo ">> Running test suite."
bundle exec rake test
result="$?"
echo

# Be done and return result of test suite.
echo ">> Done: ${result}."
exit "${result}"
