#!/bin/sh

die() {
  echo "Error: $*" >&2
  exit 1
}

ensure() {
  "$@" \
    || die "Failed to run '$*'. Aborting."
}

# Make sure we're in the repository root.
ensure cd "${0%/*}"

# Check that Bundler is available.
which bundle > /dev/null 2>&1 \
  || die "Failed to find 'bundle' executable in PATH."

# Setup required Gems for testing.
echo ">> Checking if required Gems are installed and installing missing Gems."
if ! bundle check ; then
  ensure bundle config set --local path vendor/bundle
  ensure bundle install
fi
echo

# Run the repository-owned checks.
echo ">> Running repository checks."
exec bundle exec rake
