name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        ruby: ["3.3", "3.4", "4.0"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run repository checks
        run: bundle exec rake

      - name: Upload coverage results
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          files: coverage/coverage.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

  conclusion:
    needs: tests
    if: always()
    runs-on: ubuntu-slim
    steps:
      - name: Result
        env:
          RESULT: ${{ needs.tests.result }}
        run: |
          [[ "${RESULT}" == success ]]
